name: Docker Image CI
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main


jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ gituhb.repositry_owner}}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: uses docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghrc.io/{{ gituhb.repositry_owner }}/getting-started:latest
            ghrc.io/{{ gituhb.repositry_owner }}/getting-started:${{ github.sha}}
          
